site_name: Aiuta SDK
site_url: https://sdk.aiuta.com/
site_author: Aiuta USA, Inc
site_description: >-
  Aiuta Virtual Try-On SDK

copyright: Copyright &copy; 2024 - 2025 Aiuta USA, Inc

nav:
  - About:
    - Aiuta SDK: index.md
    
  - Explore:
    - Demo Apps: about/demo-apps.md
    - Pages:
      - Welcome: about/pages/welcome-screen.md
      - Onboarding: about/pages/onboarding.md
      - Consent: about/pages/consent.md
      - Image Picker: about/pages/image-picker.md
      - Loading: about/pages/loading-screen.md
      - Results: about/pages/results-screen.md
    - Resources:
      - Prepare: about/resources/overview.md
      - Icons: about/resources/icons.md
      - Images: about/resources/images.md
      - Colors: about/resources/colors.md
      - Shapes: about/resources/shapes.md
      - Typography: about/resources/typography.md
      - Localization: about/resources/localization.md
      - Other: about/resources/other.md
    - Analytics: 
      - Events: about/analytics/analytics.md
      - Errors: about/analytics/errors.md

  - Developer:
    - Overview: developer/overview.md
    - Scheme:
      - Configuration: developer/scheme/configuration.md
      - History Images: developer/scheme/history-images.md
      - Platform Types: developer/scheme/platform-types.md

  - Android:
    - Getting started: android/aiuta/get-started.md
    
  - iOS:
    - Overview: ios/overview.md

  - Flutter:
    - Overview: flutter/overview.md
    - Quick Start:
      - Installation: flutter/installation.md
      - Configuration: flutter/configuration.md
      - Basic Usage: flutter/basic-usage.md

theme:
  name: 'material'
  custom_dir: overrides
  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - content.code.copy
    - content.tooltips
    - content.tabs.link
    - content.code.annotate
  palette:
    # Light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: media/logo/aiuta.svg
  logo: media/logo/aiuta.svg
  icon:
    logo: logo
    annotation: material/information-symbol

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - minify:
      minify_html: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aiuta-com
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/aiuta-inc
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/aiutacom
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/aiutacom/
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/AiutaCom
    - icon: aiuta
      link: https://aiuta.com

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
